### ISSUE TITLE
Warning: unlink(uploads/591108.jpg): No such file or directory

### ISSUE THREAD

**Issue by axetrodome** [axetrodome/socialmedia#14]
![image](https://user-images.githubusercontent.com/25072187/27696243-b79bee5e-5d23-11e7-83c6-9970e1827541.png)
Boss pano to kapag ganto? wala akong makitang solution dito eh stuck na ako dito sa unlink na to XD working sya nung nasa index page ko palang ineedit yung profile pic pero nung nilagay ko na sya sa edit.php tapos nag add ako ng pwedeng mga ieedit katulad ng name,username,email, password nag gaganyan na sya

**Comment by aprilmintacpineda** [comment]
Burahin mo tong line na to

https://github.com/axetrodome/socialmedia/blob/master/edit.php#L33

kasi everytime na nag a upload ka ng picture, nag a `unlink` siya ng file dun sa uploads folder mo, pero yun file an ina-unlink niya di nag e exists.

**Comment by aprilmintacpineda** [comment]
@axetrodome meron ka pang isa pang ganyan nakita ko, sigurado mag ko cause din ng error to

https://github.com/axetrodome/socialmedia/blob/master/index.php#L29

**Comment by axetrodome** [comment]
ahh wala yan boss yung sa index.php backup ko lang sya XD

**Comment by aprilmintacpineda** [comment]
aa okay sige, naayos mo na? hahaha

**Comment by axetrodome** [comment]
naayos na boss ahahahaha
