### ISSUE TITLE
flawed checking logic for login

### ISSUE THREAD

**Issue by aprilmintacpineda** [axetrodome/socialmedia#6]
![image](https://user-images.githubusercontent.com/21032419/27253947-d51ca2ce-53b0-11e7-9277-0067916bc1d3.png)

no matter what you do kahit tama na yung `username` and `password` mo laging lalabas `wrong username or password`, kasi dito sa logic ng query mo:

```
$stmt = $dbconn->prepare("SELECT * FROM users WHERE username =:username AND password=:password");
```
palaging empty ang lalabas diyan or false dahil yung checking mo sa `password=:password` mali, kasi sa database mo naka hashed yung password while sa input hindi, gayan nito, nag register ako then sa database ko eto nakalagay `37d153a06c79e99e4de5889dbe2e7c57` pero pagka nag login ako ganto magiging query diyan:

```
SELECT * FROM users WHERE username ='april' AND password='april'
```

whereas wala namang kahit anong record with a password `april` so sa madaling salita false ang lalabas.

![image](https://user-images.githubusercontent.com/21032419/27253988-7d8df084-53b1-11e7-85eb-eb28122afaeb.png)

**Comment by aprilmintacpineda** [comment]
using these codes

```
var_dump($row);
echo '<pre>', print_r($row);
die();
```

eto ang lalabas dun sa `$row` mo

![image](https://user-images.githubusercontent.com/21032419/27254006-c1107d5e-53b1-11e7-8c7d-c1ed38f5511e.png)

**Comment by axetrodome** [comment]
Sige boss salamat :D naintindihan ko na lalo :D try ko ifix lahat ng issues ahaha salamat salamat :D
