### ISSUE TITLE
Add more security

### ISSUE THREAD

**Issue by aprilmintacpineda** [axetrodome/socialmedia#7]
Add lots of error checking in your code, validate the email kung email yun dapat valid email lang pwede ilagay dun, bawal yung mga ganto `april`, `april@@pineda.com`, `april pineda@pineda.com` etc, dapat valid email like `aprilmintacpineda@gmail.com`. Also validate all fields kung may laman or empty or blank, always add validations sa lahat ng forms.

**Comment by axetrodome** [comment]
Im working on it ahahahaah thanks boss daming issue inuuna ko muna yung mahihirap bago yan XD
