### ISSUE TITLE
successfully inserted what?

### ISSUE THREAD

**Issue by aprilmintacpineda** [axetrodome/socialmedia#8]
wala pa akong ginagawa, pero lumabas na agad yung message na `Successfully Inserted!`

![image](https://user-images.githubusercontent.com/21032419/27318985-cb5e22b8-55c1-11e7-9c55-c14d4fe1e9b0.png)

**Comment by aprilmintacpineda** [comment]
nakita ko na kung anong problem niyan, dun sa login page mo pala, eto:

```
<a href="register.php?inserted">Go back to register page</a>
```

**Comment by axetrodome** [comment]
ahahahahaahaha Oo nga eh mali eh XD ibahin ko nlang yan boss ahaha
